TARGET = cli
DIRLEVEL = ..

# Possible LOGLEVEL values: dbg, info, warn, err, none
LOGLEVEL=info

# To compile using compilers with incomplete C++11 support,
# the below line might have to be uncommented:
# CXXFLAGS += -Dthread_local=

# Uncomment if GnuTLS version 3.5 or later is available
# GNUTLS=1

SOURCES=../http/cookiefile.cpp \
	main.cpp \
	utils.cpp \
	cliclient.cpp

include $(DIRLEVEL)/measurement/mk.inc
