//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tptest3.rc
//
#define IDC_MYICON                      2
#define IDGETLIST2                      3
#define IDD_TPTEST2_DIALOG              102
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDS_UDPPORT                     104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_TPTEST2                     107
#define IDI_SMALL                       108
#define IDC_TPTEST2                     109
#define IDS_STRING110                   110
#define IDC_TPTEST3                     110
#define IDC_TPTEST4                     111
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     133
#define IDD_AVANCERAT                   133
#define IDD_DIALOG2                     135
#define IDD_STANDARD                    135
#define IDD_DIALOG3                     136
#define IDD_DIALOG4                     137
#define IDD_VALJ                        137
#define IDD_DIALOG5                     141
#define IDD_ABOUTBOX1                   142
#define IDD_AVANCERAT1                  143
#define IDD_DIALOG6                     144
#define IDD_STANDARD1                   145
#define IDD_VALJ1                       146
#define IDD_STANDARD2                   147
#define IDD_STANDARD3                   148
#define IDD_STANDARD4                   149
#define IDD_STANDARD5                   150
#define IDD_ADVANCED                    151
#define IDD_PULBOX                      152
#define IDD_PULBOX1                     153
#define IDC_EDIT1                       1005
#define IDC_EDIT3                       1006
#define IDC_SERVERPORT                  1006
#define IDC_EDIT4                       1007
#define IDC_MASTER                      1007
#define IDC_MASTERPORT                  1008
#define IDC_RADIO4                      1010
#define IDC_RADIO5                      1011
#define IDC_RADIO6                      1016
#define IDC_EDIT7                       1017
#define IDC_EDIT8                       1018
#define IDC_EDIT9                       1019
#define IDC_EDIT10                      1020
#define IDC_EDIT2                       1021
#define IDC_EDIT11                      1022
#define IDC_EDIT12                      1023
#define IDC_RADIO2                      1024
#define IDC_EDIT13                      1024
#define IDAVANCERAT                     1025
#define IDC_LIST3                       1032
#define IDC_RADIO3                      1034
#define IDC_RADIO7                      1035
#define IDC_PROGRESS1                   1035
#define IDC_PROGRESS2                   1036
#define IDC_RADIO28                     1036
#define IDC_RADIO56                     1037
#define IDC_RADIO64                     1038
#define IDTILLBAKA                      1038
#define IDC_RADIO128                    1039
#define IDC_RADIO256                    1040
#define IDC_TESTAR                      1040
#define IDC_RADIO384                    1041
#define IDC_TAB1                        1041
#define IDC_RADIO512                    1042
#define IDC_RADIO640                    1043
#define IDC_START                       1043
#define IDC_RADIO1M                     1044
#define IDC_LIST2                       1044
#define IDC_SERVERLIST                  1044
#define IDC_RADIO15M                    1045
#define IDC_STANDARDTEST                1045
#define IDC_RADIO2M                     1046
#define IDC_RADIO1                      1046
#define IDC_RADIO3M                     1047
#define IDC_DISPLAY                     1047
#define IDC_RADIO8                      1047
#define IDC_RADIO4M                     1048
#define IDC_TCPBYTES                    1048
#define IDC_RADIO5M                     1049
#define IDC_UDPSPEED                    1049
#define IDC_RADIO10M                    1050
#define IDC_TCPSEND                     1050
#define IDVALJ                          1051
#define IDC_TCPRCV                      1051
#define IDC_UDPSEND                     1052
#define IDC_UDPRCV                      1053
#define IDC_LOAD                        1054
#define IDC_SENDLOAD                    1054
#define IDC_RCVLOAD                     1055
#define IDC_SERVERNAME                  1056
#define IDC_COMBO1                      1059
#define IDC_TCPINFO                     1060
#define IDC_UDPINFO                     1061
#define IDC_UDPSTART                    1063
#define IDC_TCPSTART                    1064
#define IDC_REFRESH                     1065
#define IDC_TIME                        1066
#define IDC_UDPPPS                      1067
#define IDC_UDPSIZE                     1068
#define IDC_UDPBITRATE                  1069
#define IDC_HEADER                      1071
#define IDC_PROGRESS                    1072
#define IDC_VERSION                     1073
#define IDM_INFO                        32772
#define IDM_HJALP                       32773
#define IDM_ADVANCED                    32774
#define IDM_PRINTREPORT                 32775
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
