TARG = libtptest-graph.a
LINKER = g++
CC = g++
#CDEBUG = -g

LIBS = -L/usr/local/lib -lpthread -lgd
INCLUDES = -I/Developer/SDKs/MacOSX10.4u.sdk/usr/include -I/Developer/SDKs/MacOSX10.4u.sdk/usr/include/curl
CPPFLAGS = $(INCLUDES) -DUNIX -DMACOSX -finput-charset=ISO-8859-1
LINKERFLAGS = $(LIBS)

OBJ_FILES = graphstruct.o tvutils.o

default : $(TARG)

$(TARG) : $(OBJ_FILES)
	ar -q $(TARG) $(OBJ_FILES)

clean :	
	rm *.o